In [76]:
import pandas as pd
import numpy as np

In [78]:
from sklearn.model_selection import train_test_split # data splitting
from sklearn.compose import ColumnTransformer # transform the column in 0 or 1
from sklearn.impute import SimpleImputer # missing data filled with the mean value
from sklearn.preprocessing import OneHotEncoder # relational data convert
from sklearn.preprocessing import MinMaxScaler # scalling the data on a particular scale
from sklearn.pipeline import Pipeline,make_pipeline # crete pipeline
from sklearn.feature_selection import SelectKBest,chi2 # feature of mL
from sklearn.tree import DecisionTreeClassifier # algos

In [80]:
df = pd.read_csv('dataset/placement.csv')

In [128]:
df.head(10)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1
5  8.77          6.19       1
6  5.34          7.09       0
7  6.56          6.29       0
8  6.32          6.71       0
9  7.69          7.12       1

In [84]:
df.isnull().sum() #THERE IS NO NULL VALUES IN DATASET

cgpa            0
resume_score    0
placed          0
dtype: int64

In [86]:
# Step 1 -> train/test/split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['placed']),
                                                 df['placed'],
                                                 test_size=0.2,
                                                random_state=42)

In [88]:
X_train.head()

    cgpa  resume_score
55  6.94          6.87
88  8.07          6.07
26  6.27          6.47
42  6.90          6.91
69  8.06          9.06

In [90]:
y_train

55    1
88    1
26    0
42    1
69    1
     ..
60    0
71    1
14    1
92    0
51    0
Name: placed, Length: 80, dtype: int64

In [92]:
df['cgpa'].value_counts() #11

cgpa
8.14    2
6.18    2
6.34    2
6.00    2
8.07    2
       ..
6.19    1
7.46    1
5.51    1
6.27    1
6.65    1
Name: count, Length: 89, dtype: int64

In [94]:
df['resume_score'].value_counts() #10

resume_score
7.39    2
6.18    2
7.30    2
6.19    2
7.96    2
       ..
7.19    1
7.73    1
7.02    1
7.15    1
6.61    1
Name: count, Length: 93, dtype: int64

In [96]:
# Scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,19))
])

In [108]:
# Feature selection
trf4 = SelectKBest(score_func=chi2,k=2)

In [110]:
# train the model
trf5 = DecisionTreeClassifier()

In [112]:
pipe = Pipeline([
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [114]:
# train
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 19, None))])),
                ('trf4',
                 SelectKBest(k=2,
                             score_func=<function chi2 at 0x0000024389A71760>)),
                ('trf5', DecisionTreeClassifier())])

In [116]:
# Predict
y_pred = pipe.predict(X_test)

In [118]:
y_pred

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0],
      dtype=int64)

In [122]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0

In [126]:
# export 
import pickle
pickle.dump(pipe,open('pipe1.pkl','wb'))